### PR TITLE
Fixes And Enhancements

### PR DESCRIPTION
**Pull request by XedinUnknown**
Many standardizations, optimizations and such.
- Failure now halts execution;
- `-n` flag allows retaining of installed dependencies during reset;
- Composer uses `--prefer-dist` to take maximum advantage of caching;
- Site-specific customizations go into a separate file.

### CODE REVIEW

**Comment by mecha** [comment]
The script fails when it reaches Phase 3. Upon attempting to drop the DB, it fails because the DB does not exist.

```
ERROR 1008 (HY000) at line 1: Can't drop database 'wpcr_dev'; database doesn't exist
[instash] Could not drop database
```

**Comment by XedinUnknown** [comment]
WRT the problem with dropping non-existing DB, probably the solution is that we should not drop the DB by default in non-interactive mode. Create, but not drop. Latest commits shift dropping to `drop_database()`, so it should be easier to do now.

**Review by mecha — COMMENTED** [review]
Tested and approved this fix. Works for empty interactive input as well.

**Review by XedinUnknown — COMMENTED** [review]
This works, according to @mecha

**Pull request merged**
